<?php
namespace Aspose\OCR\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OCRResponse {
	static $swaggerTypes = array(
		'Text' => 'string',
		'PartsInfo' => 'PartsInfo',
		'PagesInfo' => 'PagesInfo',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Text; // string
	public $PartsInfo; // PartsInfo
	public $PagesInfo; // PagesInfo
	public $Code; // string
	public $Status; // string
	}

